export const btn: string;
export const btnSuccess: string;
export const btnPrimary: string;
export const btnDanger: string;
export const btnWarn: string;
export const layout: string;
export const appTitle: string;
export const layoutContainer: string;
export const layoutErrorPanel: string;
